In [2]:
import sqlite3
import pandas as pd

# Define the database file name
DB_NAME = "cloud_gpu_data.db"
CSV_OUTPUT_NAME = "gpu_pricing_history.csv"

try:
    # Connect to the SQLite database
    conn = sqlite3.connect(DB_NAME)

    # Read the 'gpu_pricing' table into a pandas DataFrame
    # Note: Replace 'gpu_pricing_history' with your actual table name if different
    df_from_db = pd.read_sql_query("SELECT * FROM gpu_pricing", conn) # Corrected table name

    # Close the database connection
    conn.close()

    print(f"Successfully loaded {len(df_from_db)} records from '{DB_NAME}'.")

    # Save the DataFrame to a CSV file
    df_from_db.to_csv(CSV_OUTPUT_NAME, index=False)
    print(f"Data saved to '{CSV_OUTPUT_NAME}'.")

    # Display the first 5 rows of the loaded DataFrame
    print("\nFirst 5 rows of the loaded data from the database:")
    display(df_from_db.head())

except Exception as e:
    print(f"An error occurred: {e}")

Successfully loaded 1044 records from 'cloud_gpu_data.db'.
Data saved to 'gpu_pricing_history.csv'.

First 5 rows of the loaded data from the database:

,gpu_model,provider,vram_gb,hourly_rate_usd,pricing_type,data_source,extracted_at
0,A100 SXM,Deep Infra,80,0.89,On-Demand,ComputePrices_API,2026-07-08 21:34:53
1,A100 SXM,Deep Infra,80,0.89,On-Demand,ComputePrices_API,2026-07-08 21:34:53
2,H100 SXM,Deep Infra,80,1.79,On-Demand,ComputePrices_API,2026-07-08 21:34:53
3,H100 SXM,Deep Infra,80,1.79,On-Demand,ComputePrices_API,2026-07-08 21:34:53
4,H200,Deep Infra,141,2.19,On-Demand,ComputePrices_API,2026-07-08 21:34:53

In [3]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("cloud_gpu_data (3).db")

df = pd.read_sql_query(
    "SELECT * FROM gpu_pricing_history",
    conn
)

df.to_csv(
    "gpu_pricing_history.csv",
    index=False
)

print(df.head())
print(f"Rows: {len(df)}")

     provider provider_slug           provider_url       gpu gpu_slug  \
0  Deep Infra    deep-infra  https://deepinfra.com  A100 SXM  a100sxm
1  Deep Infra    deep-infra  https://deepinfra.com  A100 SXM  a100sxm
2  Deep Infra    deep-infra  https://deepinfra.com  H100 SXM     h100
3  Deep Infra    deep-infra  https://deepinfra.com  H100 SXM     h100
4  Deep Infra    deep-infra  https://deepinfra.com      H200     h200

   vram_gb architecture  gpu_count  max_gpus_per_node  price_per_hour_usd  \
0       80       Ampere          1                  1                0.89
1       80       Ampere          1                  1                0.89
2       80       Hopper          1                  1                1.79
3       80       Hopper          1                  1                1.79
4      141       Hopper          1                  1                2.19

   total_hourly_usd pricing_type  commitment_months currency  \
0              0.89    on_demand                NaN      USD
1              0.89     reserved                1.0      USD
2              1.79    on_demand                NaN      USD
3              1.79     reserved                1.0      USD
4              2.19    on_demand                NaN      USD

   exchange_rate_to_usd                     source_url  \
0                   1.0  https://deepinfra.com/pricing
1                   1.0  https://deepinfra.com/pricing
2                   1.0  https://deepinfra.com/pricing
3                   1.0  https://deepinfra.com/pricing
4                   1.0  https://deepinfra.com/pricing

                       last_updated         extracted_at
0  2026-06-26T09:01:16.384012+00:00  2026-07-09 20:55:57
1  2026-07-04T23:00:56.443433+00:00  2026-07-09 20:55:57
2  2026-06-26T09:01:16.425894+00:00  2026-07-09 20:55:57
3  2026-07-04T23:00:56.469873+00:00  2026-07-09 20:55:57
4  2026-06-26T09:01:16.478636+00:00  2026-07-09 20:55:57
Rows: 1051

In [4]:
import pandas as pd

# Concatenate the two DataFrames
# Assuming both dataframes have the same columns and represent similar data,
# we will use pd.concat to stack them vertically.
combined_df = pd.concat([df_from_db, df], ignore_index=True)

# Define the output CSV file name
combined_csv_filename = "combined_gpu_data.csv"

# Save the combined DataFrame to a CSV file
combined_df.to_csv(combined_csv_filename, index=False)

print(f"Successfully combined {len(df_from_db)} records from df_from_db and {len(df)} records from df_after_db.")
print(f"Total records in combined DataFrame: {len(combined_df)}.")
print(f"Combined data saved to '{combined_csv_filename}'.")

# Display the first few rows of the combined DataFrame
print("\nFirst 5 rows of the combined data:")
display(combined_df.head())

Successfully combined 1044 records from df_from_db and 1051 records from df_after_db.
Total records in combined DataFrame: 2095.
Combined data saved to 'combined_gpu_data.csv'.

First 5 rows of the combined data:

,gpu_model,provider,vram_gb,hourly_rate_usd,pricing_type,data_source,extracted_at,provider_slug,provider_url,gpu,...,architecture,gpu_count,max_gpus_per_node,price_per_hour_usd,total_hourly_usd,commitment_months,currency,exchange_rate_to_usd,source_url,last_updated
0,A100 SXM,Deep Infra,80,0.89,On-Demand,ComputePrices_API,2026-07-08 21:34:53,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A100 SXM,Deep Infra,80,0.89,On-Demand,ComputePrices_API,2026-07-08 21:34:53,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,H100 SXM,Deep Infra,80,1.79,On-Demand,ComputePrices_API,2026-07-08 21:34:53,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,H100 SXM,Deep Infra,80,1.79,On-Demand,ComputePrices_API,2026-07-08 21:34:53,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,H200,Deep Infra,141,2.19,On-Demand,ComputePrices_API,2026-07-08 21:34:53,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Display basic statistics about the combined dataset
print("Dataset Overview:")
print(f"Total records: {len(combined_df)}")
print(f"\nProviders in dataset: {combined_df['provider'].nunique()}")
print(f"Unique GPU models: {combined_df['gpu_model'].nunique()}")
print(f"\nPricing statistics:")
print(combined_df['hourly_rate_usd'].describe())
print(f"\nMissing values:")
print(combined_df.isnull().sum())

Dataset Overview:
Total records: 2095

Providers in dataset: 48
Unique GPU models: 55

Pricing statistics:
count    1044.000000
mean        1.952229
std         2.108370
min         0.040000
25%         0.565500
50%         1.290000
75%         2.590000
max        18.000000
Name: hourly_rate_usd, dtype: float64

Missing values:
gpu_model               1051
provider                   0
vram_gb                    0
hourly_rate_usd         1051
pricing_type               0
data_source             1051
extracted_at               0
provider_slug           1044
provider_url            1044
gpu                     1044
gpu_slug                1044
architecture            1044
gpu_count               1044
max_gpus_per_node       1044
price_per_hour_usd      1044
total_hourly_usd        1044
commitment_months       1943
currency                1044
exchange_rate_to_usd    1044
source_url              1044
last_updated            1044
dtype: int64